#!/bin/sh
###############################################################################
# Specify nodes, processors per node and maximum running time
###############################################################################

#PBS -l select=5:ncpus=24:mpiprocs=24
#PBS -l walltime=1:00:00

###############################################################################
# Enter directory and set PATH
###############################################################################

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH

###############################################################################
# Run OpenMC
###############################################################################

MV2_ENABLE_AFFINITY=0
export MV2_ENABLE_AFFINITY

#PBS -k eo
OMP_NUM_THREADS=1
export OMP_NUM_THREADS
mpirun -ppn 24 -bind-to socket -map-by socket $HOME/openmc-samuelshaner/build/bin/openmc