#!/bin/sh
###############################################################################
# Specify nodes, processors per node and maximum running time
###############################################################################

#PBS -l select=1:ncpus=36:mpiprocs=36:cputype=broadwell
#PBS -l walltime=12:00:00

###############################################################################
# Enter directory and set PATH
###############################################################################

cd $PBS_O_WORKDIR
PATH=$PBS_O_PATH

###############################################################################
# Run OpenMC
###############################################################################

MV2_ENABLE_AFFINITY=0
export MV2_ENABLE_AFFINITY

#PBS -k eo
OMP_NUM_THREADS=1
export OMP_NUM_THREADS
mpirun -ppn 36 -bind-to socket -map-by socket $HOME/openmc-samuelshaner/build/bin/openmc